#!/usr/bin/env python3
"""
Simple Fast Signal — canonical writer (schema v2).

Trading rules are UNCHANGED (thresholds, window, return formula).
This version only hardens execution/reliability:

  * First valid canonical file wins and is never overwritten (exclusive create).
  * DATA_ERROR is never canonical: failures go to simple_fast/attempts/ so a
    recovery run can still produce the canonical file.
  * Every run (success, failure, skip) leaves an attempt artifact for audit.
  * Every canonical file is stamped with its trigger role, run id, latency and a
    `live_eligible` flag. A file generated after the live deadline is kept for
    audit but is explicitly NOT consumable for a live decision.
  * Boundary selection tolerates an early trigger (clock skew) so a run fired a
    few seconds before 18:00 UTC cannot target yesterday's boundary.
  * Binance requests retry on network/HTTP errors instead of failing on the
    first exception.

Canonical path : simple_fast/YYYY-MM-DD.json            (UTC date of the 18:00 boundary)
Attempt path   : simple_fast/attempts/YYYY-MM-DD/<HHMMSS>_<role>_<run>.json
"""
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

SCHEMA_VERSION = 2
BASE_URL = "https://data-api.binance.vision/api/v3/klines"
UTC = timezone.utc
DUBAI = timezone(timedelta(hours=4))  # UTC+4 year-round, no DST

# Frozen Simple signal thresholds — DO NOT CHANGE (strategy logic).
SYMBOL_THRESHOLDS = {
    "PUMPUSDT": 6.5,
    "ENAUSDT": 1.0,
    "HOLOUSDT": 2.0,
}

BOUNDARY_HOUR_UTC = 18                 # 18:00 UTC = 22:00 Dubai
EARLY_TRIGGER_TOLERANCE = timedelta(minutes=10)
LIVE_DEADLINE = timedelta(minutes=5)   # canonical must be generated by 18:05 UTC / 22:05 Dubai
FINAL_MINUTE_WAIT_SECONDS = 120        # max wait for Binance to publish the closed 17:59 minute
HTTP_RETRIES = 6

OUT_DIR = Path(os.environ.get("SIMPLE_FAST_DIR", "simple_fast"))


# ---------------------------------------------------------------- utilities
def utcnow():
    return datetime.now(UTC)


def iso(dt):
    return dt.isoformat() if dt else None


def log(msg):
    print(f"[{utcnow().strftime('%H:%M:%S.%f')[:-3]}Z] {msg}", flush=True)


def select_boundary(now):
    """Return the 18:00 UTC boundary this run belongs to.

    If the trigger fires up to EARLY_TRIGGER_TOLERANCE before 18:00 UTC, the run
    belongs to TODAY's boundary and waits for it, rather than silently targeting
    yesterday's (already-written) boundary.
    """
    today = now.replace(hour=BOUNDARY_HOUR_UTC, minute=0, second=0, microsecond=0)
    if now >= today - EARLY_TRIGGER_TOLERANCE:
        return today
    return today - timedelta(days=1)


def http_json(url):
    last_exc = None
    for attempt in range(1, HTTP_RETRIES + 1):
        try:
            with urllib.request.urlopen(url, timeout=10) as resp:
                return json.loads(resp.read().decode())
        except (urllib.error.URLError, TimeoutError, ConnectionError, json.JSONDecodeError) as exc:
            last_exc = exc
            log(f"HTTP attempt {attempt}/{HTTP_RETRIES} failed: {exc!r}")
            time.sleep(min(2 ** (attempt - 1), 8))
    raise RuntimeError(f"Binance request failed after {HTTP_RETRIES} attempts: {last_exc!r}")


def get_one_minute(symbol, minute_start):
    start_ms = int(minute_start.timestamp() * 1000)
    params = urllib.parse.urlencode({
        "symbol": symbol,
        "interval": "1m",
        "startTime": start_ms,
        "endTime": start_ms + 59_999,
        "limit": 1,
    })
    rows = http_json(f"{BASE_URL}?{params}")
    if not rows:
        return None
    row = rows[0]
    if int(row[0]) != start_ms:
        return None
    return row


def get_completed_minute(symbol, minute_start, deadline):
    """Poll until the exact minute exists AND its close time is in the past."""
    while True:
        row = get_one_minute(symbol, minute_start)
        if row is not None and int(row[6]) < int(utcnow().timestamp() * 1000):
            return row
        if utcnow() >= deadline:
            return None
        time.sleep(2)


def write_json_exclusive(path, payload):
    """Create file only if it does not exist. Returns False if it already exists."""
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(path, "x", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
            fh.write("\n")
        return True
    except FileExistsError:
        return False


def write_attempt(boundary, role, run_id, payload):
    stamp = utcnow().strftime("%H%M%S")
    path = OUT_DIR / "attempts" / boundary.strftime("%Y-%m-%d") / f"{stamp}_{role}_{run_id}.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    log(f"Attempt artifact: {path}")


# --------------------------------------------------------------------- main
def main():
    started = utcnow()
    role = os.environ.get("TRIGGER_ROLE", "MANUAL")
    run_id = os.environ.get("GITHUB_RUN_ID", "local")
    run_attempt = os.environ.get("GITHUB_RUN_ATTEMPT", "1")

    boundary = select_boundary(started)
    canonical = OUT_DIR / f"{boundary.strftime('%Y-%m-%d')}.json"
    log(f"role={role} run={run_id}/{run_attempt} boundary={iso(boundary)} canonical={canonical}")

    run_meta = {
        "trigger_role": role,
        "github_run_id": run_id,
        "github_run_attempt": run_attempt,
        "script_started_at_utc": iso(started),
    }

    # 1) Immutability: if a canonical file already exists, never touch it.
    if canonical.exists():
        log("Canonical file already exists -> SKIPPED_EXISTS (no recomputation).")
        write_attempt(boundary, role, run_id, {
            "schema_version": SCHEMA_VERSION,
            "boundary_utc": iso(boundary),
            "outcome": "SKIPPED_EXISTS",
            **run_meta,
        })
        return 0

    # 2) Early trigger: wait for the boundary itself.
    if started < boundary:
        wait_s = (boundary - started).total_seconds()
        log(f"Triggered {wait_s:.1f}s before boundary; waiting.")
        time.sleep(wait_s)

    signal_open_minute = boundary - timedelta(days=1)
    signal_close_minute = boundary - timedelta(minutes=1)
    final_minute_deadline = max(utcnow(), boundary) + timedelta(seconds=FINAL_MINUTE_WAIT_SECONDS)

    symbols, all_ok = {}, True
    for symbol, threshold in SYMBOL_THRESHOLDS.items():
        try:
            first = get_one_minute(symbol, signal_open_minute)
            last = get_completed_minute(symbol, signal_close_minute, final_minute_deadline)
            if first is None or last is None:
                raise RuntimeError("Exact signal open or completed final minute unavailable")

            candle_open = float(first[1])
            candle_close = float(last[4])
            return_pct = (candle_close / candle_open - 1) * 100
            qualified = return_pct >= threshold
            symbols[symbol] = {
                "status": "OK",
                "open": candle_open,
                "close": candle_close,
                "return_pct": return_pct,
                "threshold_pct": threshold,
                "qualified": qualified,
                "decision": "BUY" if qualified else "NO TRADE",
                "open_minute_utc": iso(signal_open_minute),
                "close_minute_utc": iso(signal_close_minute),
                "final_minute_close_time_ms": int(last[6]),
            }
        except Exception as exc:  # noqa: BLE001 — fail closed per symbol
            all_ok = False
            symbols[symbol] = {"status": "DATA_ERROR", "threshold_pct": threshold, "error": str(exc)}
            log(f"{symbol}: DATA_ERROR {exc!r}")

    generated = utcnow()
    latency_s = (generated - boundary).total_seconds()
    live_eligible = all_ok and generated <= boundary + LIVE_DEADLINE

    payload = {
        "schema_version": SCHEMA_VERSION,
        "generated_at_utc": iso(generated),
        "boundary_utc": iso(boundary),
        "boundary_dubai": iso(boundary.astimezone(DUBAI)),   # fixed: real +04:00 offset
        "signal_window_start_utc": iso(signal_open_minute),
        "signal_window_end_utc": iso(boundary),
        "latency_seconds_after_boundary": round(latency_s, 3),
        "live_deadline_utc": iso(boundary + LIVE_DEADLINE),
        "live_eligible": live_eligible,
        "immutable": True,
        "status": "OK" if all_ok else "DATA_ERROR",
        **run_meta,
        "symbols": symbols,
    }
    print(json.dumps(payload, indent=2))

    # 3) DATA_ERROR is never canonical — recorded as an attempt so recovery can still run.
    if not all_ok:
        write_attempt(boundary, role, run_id, {**payload, "outcome": "DATA_ERROR_NOT_CANONICAL"})
        return 1

    # 4) First valid result wins. Exclusive create guards against a same-runner race.
    if write_json_exclusive(canonical, payload):
        log(f"Canonical written: {canonical} live_eligible={live_eligible} latency={latency_s:.1f}s")
        write_attempt(boundary, role, run_id, {**payload, "outcome": "CANONICAL_WRITTEN"})
    else:
        log("Canonical appeared during run -> not overwritten.")
        write_attempt(boundary, role, run_id, {**payload, "outcome": "SKIPPED_EXISTS_LATE"})
    return 0


if __name__ == "__main__":
    sys.exit(main())
